### ISSUE TITLE
possible unsafe use of unserialize

### ISSUE THREAD

**Issue by danmarsden** [devlionco/moodle-local_lionai_reports#19]
in your local_lionai_reports_cr_unserialize() function you make use of an unsafe PHP function "unerialize" - it's hard to trace how this is used, (and I suspect there are some issues with your frankenstyle naming conversion as I see some internal calls to "cr_unserialize" which doesn't exist as a function.

If this data is coming from user input or built using user input it could be a serious security risk.

this post here covers the risks and you might find useful:
https://www.invicti.com/blog/web-security/untrusted-data-unserialize-php/

Please check to make sure it's not allowing users (even admins) to pass unfiltered/uncleaned data into this function.

**Comment by Uriel-Cerem-Devlion** [comment]
Hi @danmarsden , 

I dwelved into the issue, because the link that you mentioned really concerning about the "unserialize" problem. As far as I can tell, the only thing that come from a user is the SQL query that we try to export to configutable_reports. Moreover, the function "userialize" is only used in the locallib function "local_lionai_reports_cr_unserialize" which was built to provide the reverse of the serialize function "local_lionai_reports_cr_serialize", but "local_lionai_reports_cr_unserialize" is never used (if this is a blocker, let me know to delete it).
As for "cr_unserialize", is is a function from configutable_reports, which we use after we make sure that the configutable_reports exists in the system - so in that case if it is risky I blame them 😅

I would like your answer anout this isuue and about the code as I explained, because we really tried to avoid security issues in general.

**Comment by danmarsden** [comment]
if your local function isn't used - best to remove it - "unserialize" is one of those nasty things in php code that will often get picked up for further investigation during security reviews - if it's not used, it will likely save some poor developer given the responsibility to review your code a bunch of time. :-)

**Comment by Uriel-Cerem-Devlion** [comment]
thanks for the advice! I deleted the function
